#!/usr/bin/env python3
"""Assert every configured path accessor resolves to something that exists.

WHY THIS EXISTS
---------------
When the overlay's layout is renamed, ``config.yaml`` is the seam: every tool
reaches owner data through ``automation/shared/config.py``'s accessors, and one
un-updated ``paths.*`` key means a tool silently reads or writes the wrong
address. Verifying that by hand — "all current accessors were verified against
existing destinations" — is a real step in a cutover that had no command. This
is that command.

Two properties, both fail-closed:

  * **The accessor list is discovered, never typed.** Every module-level
    ``*_path`` / ``*_dir`` / ``*_root`` function in ``config.py`` that takes no
    required argument is enumerated at runtime. A newly added accessor is
    therefore checked the day it lands.
  * **An accessor this file cannot classify is a FAILURE, not a skip.** Whether a
    path should be a file or a directory is knowledge the name does not carry
    (``story_bank_path`` is a directory; ``calendar_path`` is a file), so the
    kinds live in ``EXPECTED`` below. Discovery and classification then check
    each other: an accessor missing from ``EXPECTED`` reports UNCLASSIFIED and
    exits 1, and an ``EXPECTED`` key that no longer exists reports STALE and
    exits 1. The table cannot rot silently in either direction.

It also refuses to run at all against the fictional example persona: a green
report that validated ``config.example.yaml`` is worse than no report.

Usage::

    .venv/bin/python automation/cutover/check_configured_paths.py

Exit codes::

    0  every REQUIRED accessor resolves to an existing destination of the right
       kind (optional ones may be absent and are reported SKIP)
    1  something is MISSING, of the WRONG-KIND, UNCLASSIFIED, or STALE
    3  REFUSED — no config could be loaded, or it resolved to the tracked
       example persona (config.example.yaml)
"""
from __future__ import annotations

import argparse
import importlib.util
import inspect
import sys
from pathlib import Path
from typing import Sequence

FILE, DIR = "file", "dir"

OK = "OK"
MISSING = "MISSING"
WRONG_KIND = "WRONG-KIND"
SKIP = "SKIP"
UNCLASSIFIED = "UNCLASSIFIED"
STALE = "STALE"
ERROR = "ERROR"

FAILING = (MISSING, WRONG_KIND, UNCLASSIFIED, STALE, ERROR)

ACCESSOR_SUFFIXES = ("_path", "_dir", "_root")

# key -> (kind, required, why it is optional)
#
# REQUIRED means "a working configuration always points this at something that
# already exists". OPTIONAL means the destination materializes when a tool first
# writes it (a derived card, a generated calendar, an append-only log, a store
# that may be disabled), so its absence is a fact to report, not a red gate.
EXPECTED: dict[str, tuple[str, bool, str]] = {
    "config_path": (FILE, True, ""),
    "profile_md_path": (FILE, True, ""),
    "baseline_path": (FILE, True, ""),
    "reference_docx_path": (FILE, True, ""),
    "applications_root": (DIR, True, ""),
    "candidate_dir": (DIR, True, ""),
    "overlay_root": (DIR, True, ""),

    "tailoring_card_path": (
        FILE, False, "derived artifact; the resume-writer skill builds it"),
    "calendar_path": (
        FILE, False, "generated by status.py --sync-calendar"),
    "applications_log_path": (
        FILE, False, "derived skip-log; written on the first --sync-log"),
    "applications_jsonl_path": (
        FILE, False, "append-only skip-log; written on the first recorded posting"),
    "company_search_log_path": (
        FILE, False, "written on the first recorded company search"),
    "company_levels_path": (
        FILE, False, "compensation cache; written on the first import"),
    "blacklist_path": (
        FILE, False, "candidate blacklist overlay; optional by design"),
    "discoveries_dir": (
        DIR, False, "materializes when job-search writes its first scan"),
    "companies_root": (
        DIR, False, "materializes with the first company dossier"),
    "story_bank_path": (
        DIR, False, "materializes with the first behavioral story"),
    "search_profiles_dir": (
        DIR, False, "materializes with the first saved search profile"),
    "data_root": (
        DIR, False, "the raw-data-layer store is DISABLED when unset"),
}


def _find_repo_root(start: Path) -> Path:
    """The nearest ancestor holding a ``.git`` entry (a FILE in a worktree)."""
    for candidate in (start, *start.parents):
        if (candidate / ".git").exists():
            return candidate
    raise SystemExit(
        f"check_configured_paths: no .git entry above {start} — cannot locate "
        f"the repo root")


REPO_ROOT = _find_repo_root(Path(__file__).resolve().parent)


def load_config_module(root: Path = REPO_ROOT, module_name: str = "_jobhunt_config"):
    """Load ``automation/shared/config.py`` without making automation a package."""
    path = root / "automation" / "shared" / "config.py"
    if not path.is_file():
        raise FileNotFoundError(path)
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"could not create an import spec for {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    try:
        spec.loader.exec_module(module)
    except BaseException:
        sys.modules.pop(module_name, None)
        raise
    return module


def discover_accessors(config_module) -> list[str]:
    """Every zero-argument ``*_path`` / ``*_dir`` / ``*_root`` accessor, sorted."""
    found: list[str] = []
    for name, function in inspect.getmembers(config_module, inspect.isfunction):
        if name.startswith("_") or not name.endswith(ACCESSOR_SUFFIXES):
            continue
        if function.__module__ != config_module.__name__:
            continue  # imported from a sibling module, not a config accessor
        signature = inspect.signature(function)
        required = [
            parameter for parameter in signature.parameters.values()
            if parameter.default is inspect.Parameter.empty
            and parameter.kind in (parameter.POSITIONAL_ONLY,
                                   parameter.POSITIONAL_OR_KEYWORD,
                                   parameter.KEYWORD_ONLY)
        ]
        if required:
            continue  # e.g. skill_references_dir(skill) — not a single destination
        found.append(name)
    return sorted(found)


def refusal_reason(config_module) -> str | None:
    """Why this check must not run, or None when it may."""
    try:
        active = config_module.config_path()
    except Exception as error:  # ConfigNotFound, ConfigError, unreadable YAML …
        return (f"no configuration could be loaded ({type(error).__name__}: {error}). "
                f"A path check with no config would validate nothing.")
    example = getattr(config_module, "EXAMPLE_CONFIG", None)
    example_name = getattr(config_module, "EXAMPLE_CONFIG_FILENAME",
                           "config.example.yaml")
    is_example = active.name == example_name
    if example is not None:
        try:
            is_example = is_example or active.resolve() == Path(example).resolve()
        except OSError:
            pass
    if is_example:
        return (f"configuration resolved to the fictional example persona "
                f"({active}). Reporting this tree green would certify the "
                f"placeholder, not the owner's data.")
    return None


def check_accessor(config_module, name: str) -> tuple[str, Path | None, str]:
    """Return ``(status, resolved_path_or_None, note)`` for one accessor."""
    kind, required, optional_note = EXPECTED[name]
    try:
        value = getattr(config_module, name)()
    except Exception as error:
        return ERROR, None, f"{type(error).__name__}: {error}"

    if value is None:
        if required:
            return MISSING, None, "accessor returned None"
        return SKIP, None, optional_note or "not configured"

    path = Path(value)
    if kind == FILE and path.is_file():
        return OK, path, ""
    if kind == DIR and path.is_dir():
        return OK, path, ""
    if path.exists():
        actual = DIR if path.is_dir() else "other"
        if path.is_file():
            actual = FILE
        return WRONG_KIND, path, f"expected a {kind}, found a {actual}"
    if required:
        return MISSING, path, f"expected a {kind}; nothing exists at this path"
    return SKIP, path, optional_note or "absent"


def report(config_module, out) -> int:
    discovered = discover_accessors(config_module)
    rows: list[tuple[str, str, str, str]] = []
    failures: list[str] = []

    for name in discovered:
        if name not in EXPECTED:
            rows.append((UNCLASSIFIED, name, "-",
                         "new accessor in config.py — add its kind to "
                         "check_configured_paths.EXPECTED"))
            failures.append(name)
            continue
        status, path, note = check_accessor(config_module, name)
        rows.append((status, name, "-" if path is None else str(path), note))
        if status in FAILING:
            failures.append(name)

    for name in sorted(set(EXPECTED) - set(discovered)):
        rows.append((STALE, name, "-",
                     "EXPECTED names an accessor config.py no longer has — "
                     "remove the row or restore the accessor"))
        failures.append(name)

    status_width = max(len(row[0]) for row in rows)
    name_width = max(len(row[1]) for row in rows)
    print(f"configured paths — {len(discovered)} accessor(s) discovered in "
          f"automation/shared/config.py", file=out)
    print(f"config: {config_module.config_path()}\n", file=out)
    for status, name, path, note in rows:
        line = f"{status.ljust(status_width)}  {name.ljust(name_width)}  {path}"
        print(line, file=out)
        if note:
            print(f"{' ' * (status_width + name_width + 2)}  -> {note}", file=out)

    skipped = [row[1] for row in rows if row[0] == SKIP]
    passed = [row[1] for row in rows if row[0] == OK]
    print("", file=out)
    if skipped:
        print("skipped (NOT passes — optional destinations that do not exist yet): "
              + ", ".join(skipped), file=out)
    if failures:
        print(f"RED: {', '.join(failures)} ({len(failures)} of {len(rows)} "
              f"accessors did not resolve)", file=out)
        return 1
    print(f"ALL GREEN ({len(passed)} accessors resolved, {len(skipped)} skipped)",
          file=out)
    return 0


def build_parser() -> argparse.ArgumentParser:
    return argparse.ArgumentParser(
        prog="check_configured_paths.py",
        description="Assert every config.*_path()/_dir()/_root() accessor resolves "
                    "to an existing destination of the right kind.")


def main(argv: Sequence[str] | None = None, out=None) -> int:
    out = out or sys.stdout
    build_parser().parse_args(list(argv) if argv is not None else None)
    try:
        config_module = load_config_module()
    except Exception as error:
        print(f"REFUSED: could not load automation/shared/config.py "
              f"({type(error).__name__}: {error})", file=out)
        return 3
    reason = refusal_reason(config_module)
    if reason is not None:
        print(f"REFUSED: {reason}", file=out)
        return 3
    return report(config_module, out)


if __name__ == "__main__":
    sys.exit(main())
